name: Secrets variable strategy

on:
  workflow_dispatch:
    inputs:
      sel_env:
        type: choice
        options:
          - 'SANDBOX'
          - 'STAGING'
          - 'PRODUCTION'
        default: 'PRODUCTION'
        required: true
        description: Pick an environment to deploy

jobs:
  first-job:
    env:
      SUP_TEST: ${{ format('{0}_SUP_TEST', github.event.inputs.sel_env) }}
      SET_TEST: ${{ format('{0}_SET_TEST', github.event.inputs.sel_env) }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ env.SUP_TEST }} ${{ secrets[env.SUP_TEST] }}
      - run: echo ${{ env.SET_TEST }} ${{ secrets[env.SET_TEST] }}

  second-job:
    runs-on: ubuntu-latest
    needs: [first-job]
    steps:
      - run: echo ${{ env.SUP_TEST }} ${{ secrets[env.SUP_TEST] }}
      - run: echo ${{ env.SET_TEST }} ${{ secrets[env.SET_TEST] }}
      
  third-job:
    needs: [second-job]
    env:
      SET_TEST: ${{ format('{0}_SET_TEST', github.event.inputs.sel_env) }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ env.SUP_TEST }} ${{ secrets[env.SUP_TEST] }}
      - run: echo ${{ env.SET_TEST }} ${{ secrets[env.SET_TEST] }}
